version: '3.3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/temp-dev
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mongodb:
    image: mongo
    volumes:
      - dbdata:/data/db
    ports:
      - "27017:27017"
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
