export default {
  CustomerRegister: {
    type: 'object',
    required: ['eventName', 'eventTime', 'areaId', 'name'],
    properties: {
      eventName: {
        type: 'string',
        description: 'Unique identifier of the event',
        example: 'CustomerRegister',
        pattern: 'CustomerRegister',
      },
      eventTime: {
        type: 'string',
        description: 'Time when the provider created the area',
        example: '2021-01-26T09:37:37Z',
        format: 'date-time',
      },
      areaId: {
        type: 'string',
        description: 'Unique identifier of the area',
        example: '5emh/t5chEyN8S68yG1Rug==',
        minLength: 1,
        maxLength: 36,
      },
      name: {
        type: 'string',
        description: 'Name of the area',
        example: 'xotto-area-1',
        minLength: 1,
        maxLength: 256,
      },
    },
  },
  PlayerRegistration: {
    type: 'object',
    required: [
      'eventName',
      'eventTime',
      'playerId',
      'fullName',
      'postCode',
      'place',
      'area',
      'country',
      'citizenship',
      'street',
      'number',
      'brithDate',
      'brithLocation',
      'brithName',
    ],
    properties: {
      eventName: {
        type: 'string',
        description: 'Unique identifier of the event',
        example: 'PlayerRegistration',
        pattern: 'PlayerRegistration',
      },
      eventTime: {
        type: 'string',
        description: 'Time when the provider created the area',
        example: '2021-01-26T09:37:37Z',
        format: 'date-time',
      },
      playerId: {
        type: 'string',
        description: 'Unique identifier of the area',
        example: '5emh/t5chEyN8S68yG1Rug==',
        minLength: 1,
        maxLength: 36,
      },
      username: {
        type: 'string',
        description: 'The username of the player at the provider',
        example: 'janeDoe12',
        minLength: 0,
        maxLength: 256,
      },
      fullName: {
        type: 'string',
        description: 'The username of the player at the provider',
        example: 'Jane Doe',
        minLength: 1,
        maxLength: 256,
      },
      postCode: {
        type: 'string',
        description: 'The postcode of the player"s place of residence',
        example: '12345',
        minLength: 1,
        maxLength: 256,
      },
      place: {
        type: 'string',
        description: 'The place of residence of the address of the player',
        example: 'Berlin,Germany',
        minLength: 1,
        maxLength: 256,
      },
      area: {
        type: 'string',
        description: 'The state of residence of the player',
        example: '12345',
        minLength: 1,
        maxLength: 256,
      },
      country: {
        type: 'string',
        description: 'The country of the specified address',
        example: 'Germany',
        minLength: 1,
        maxLength: 256,
      },
      citizenship: {
        type: 'string',
        description: 'The nationality of the player',
        example: 'American',
        minLength: 1,
        maxLength: 256,
      },
      street: {
        type: 'string',
        description: 'The street of the address of the player',
        example: 'Berlin,Germany',
        minLength: 1,
        maxLength: 256,
      },
      number: {
        type: 'integer',
        description: 'The house number(s) of the player"s address',
        example: '245',
        minimum: 1,
      },
      brithDate: {
        type: 'string',
        description: 'Date of birth of the player',
        example: '2021-01-26',
        format: 'date',
      },
      brithLocation: {
        type: 'string',
        description: 'Birth place of the player',
        example: 'Berlin,Germany',
        minLength: 1,
        maxLength: 256,
      },
      brithName: {
        type: 'string',
        description: 'Birth name of the player',
        example: 'John Doe',
        minLength: 1,
        maxLength: 256,
      },
      status: {
        type: 'boolean',
        description: 'Data types shows for boolSpecifies',
        example: true,
      },
      automaticProfitTransactionmoneyAmount: {
        type: 'string',
        description:
          'limit , from which winnings are automatically paid to the player.',
        example: '23.01',
        minimum: 0,
        pattern: '^[0-9]*.[0-9][0-9]$',
      },
    },
  },
}
