enum statusconstant {
  OBJECT_STATUS_ENABLED = 1,
  OBJECT_STATUS_DISABLED,
  OBJECT_STATUS_SUSPENDED3,
  OBJECT_STATUS_PENDING,
  OBJECT_STATUS_DELETED,
  OBJECT_STATUS_ACTIVE,
  OBJECT_STATUS_COMPLETED,
  OBJECT_STATUS_EXPIRED,
  OBJECT_STATUS_REJECTED,
}

export default {
  SERVER_HOST: 'localhost',
  SERVER_PORT: 3000,

  REQUEST_OK: 200,
  REQUEST_CREATED: 201,
  REQUEST_BAD_REQUEST: 400,
  REQUEST_UNAUTHORIZED: 401,
  REQUEST_FORBIDDEN: 403,
  REQUEST_NOT_FOUND: 404,
  REQUEST_METHOD_NOT_ALLOWED: 405,
  REQUEST_CONFLICT: 409,
  REQUEST_INTERNAL_SERVICE_ERROR: 500,
  REQUEST_SERVICE_UNAVAILABLE: 503,

  statusconstant,
  MAX_FOLDER_SIZE: 50000,
  FILE_RECHECK_TIME: 5000,
  MAX_EVENT_IN_FILE: 100,
  MAX_FILE_SIZE: 50000,
  FILE_SAVE_FAILED: 'Failed to save file',
  FILE_SAVE_SUCCESS: 'Event saved successfully',
}
